name: Build immortal-zombie

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Update repos
        run: xmake repo -u

      - name: Configure & install packages
        run: xmake f -m release -y --target_type=server

      - name: Build
        run: xmake

      - name: Find DLL
        run: Get-ChildItem -Recurse -Filter *.dll | Select-Object FullName
        shell: pwsh
        
      - name: Package mod
        run: |
          mkdir output
          for /r %%f in (*.dll) do copy "%%f" output\immortal-zombie.dll
          copy manifest.json output\manifest.json
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: immortal-zombie
          path: output/
