name: Build immortal-zombie

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Update repos
        run: xmake repo -u

      - name: Configure & install packages
        run: xmake f -m release -y

      - name: Build
        run: xmake

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: immortal-zombie-dll
          path: bin/windows/x64/release/immortal-zombie/
